utils::globalVariables(
  c(
    "Estimated_Factors",
    "Factor",
    "Feature",
    "Probability",
    "Reference_Factors",
    "Sample",
    "Similarity",
    "Uncertainty",
    "Value",
    "txt_col"
  )
)